Projects/Exam/config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :comments
  resources :projects
  resources :tasks
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root 'projects#index'
end

Projects/Exam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
  <head>
    <title>Tasker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
   
    
   
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "Main", signup_path, class: "navbar-brand", id: "logo"%>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
                  <%= link_to "Projects", projects_path, class: "nav-item nav-link", id: "project"%>
                  <%= link_to "Tasks", tasks_path, class: "nav-item nav-link", id: "task"%>
                  <%= link_to "Comments", comments_path, class: "nav-item nav-link", id: "comment"%>
                  
          </div>
          <div class="navbar-nav ms-auto">
                
                
                <% if logged_in? %>
                  <a class="nav-item nav-link disabled" href="#">
                    <%= current_user.username%>
                  </a>
                  <li class="nav-item">
                  <%= button_to "LogOut", logout_path, class: "nav-link", method: :delete %>
                  </li>
                <%else%>
                <li class="nav-item">
                  <%= link_to "SignIn", login_path, class: "nav-link", id: "Sign In"%>
                </li>
                <li class="nav-item">
                  <%= link_to "SignUp", signup_path, class: "nav-link", id: "sign up"%>
                </li>
                <%end%>
          </div>
          
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>